## 00. PyTorch Fundamentals

In [1]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.7770, 0.0080, 0.4007],
        [0.2273, 0.9376, 0.6201],
        [0.6019, 0.5345, 0.4754],
        [0.4485, 0.1947, 0.3350],
        [0.4242, 0.9622, 0.1397]])


In [2]:
import numpy as np

In [3]:
import matplotlib as plt

In [4]:
import pandas as pd

In [8]:
print(torch.__version__)

2.4.0+cpu


## Introduction to tensors 

### Creating tensors

In [10]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim

0

In [13]:
scalar.item()

7

In [14]:
#Vector 
vector = torch.tensor([7 ,7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([2])

In [17]:
scalar.shape

torch.Size([])

In [26]:
#Matrix
MATRIX = torch.tensor([[7, 8],[9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [29]:
MATRIX[0]

tensor([7, 8])

In [30]:
MATRIX[1]

tensor([ 9, 10])

In [31]:
MATRIX.shape

torch.Size([2, 2])

In [33]:
# Tensor 
TENSOR = torch.tensor([[[1,2,3],[2,3,4],[4,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [4, 5, 6]]])

In [34]:
TENSOR.ndim

3

In [35]:
TENSOR.shape

torch.Size([1, 3, 3])

In [53]:
TENSOR[0,2,2]

tensor(6)

### Random Tensors 

Important because nn starts with tensors with random numbers, and adjust those rand num to better represent data

In [69]:
#create a random tensor of size (3,4)
random_tensor = torch.rand (3,4)
random_tensor

tensor([[0.7448, 0.5692, 0.9970, 0.8709],
        [0.0128, 0.6656, 0.9496, 0.2256],
        [0.3803, 0.6724, 0.6166, 0.0694]])

In [70]:
random_tensor.ndim

2

In [76]:
#random tansor same shape as image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [78]:
random_image_size_tensor[1,5,1]

tensor(0.9001)

False