## 00. PyTorch Fundamentals

In [ ]:
a =2

In [2]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.1620, 0.5861, 0.9542],
        [0.0654, 0.0600, 0.2213],
        [0.4378, 0.0327, 0.4238],
        [0.9058, 0.2724, 0.2066],
        [0.9498, 0.3673, 0.3454]])


In [3]:
import numpy as np

In [4]:
import matplotlib as plt

In [5]:
import pandas as pd

In [6]:
print(torch.__version__)

2.4.0+cpu


## Introduction to tensors 

### Creating tensors

In [7]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
scalar.item()

7

In [10]:
#Vector 
vector = torch.tensor([7 ,7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
scalar.shape

torch.Size([])

In [14]:
#Matrix
MATRIX = torch.tensor([[7, 8],[9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX[0]

tensor([7, 8])

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# Tensor 
TENSOR = torch.tensor([[[1,2,3],[2,3,4],[4,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [4, 5, 6]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0,2,2]

tensor(6)

### Random Tensors 

Important because nn starts with tensors with random numbers, and adjust those rand num to better represent data

In [22]:
#create a random tensor of size (3,4)
random_tensor = torch.rand (3,4)
random_tensor

tensor([[0.3328, 0.9415, 0.1598, 0.5102],
        [0.2912, 0.5482, 0.5718, 0.3222],
        [0.8422, 0.4279, 0.6176, 0.4353]])

In [23]:
random_tensor.ndim

2

In [24]:
#random tansor same shape as image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [25]:
random_image_size_tensor[1,5,1]

tensor(0.6836)

In [26]:
one_to_ten= torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [31]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])